-- *******************************************************************************************
--  DML - Data manipulation language 
--  Faz os inserts de registros de base no banco de dados - tabelas tradicionais
-- *******************************************************************************************


-- Insert valores na tabela PESSOA. Valor piloto: vanity value... :) 
-- INSERT INTO PESSOA (NOME, SOBRENOME, ANO_NASC, BIO) VALUES('JULIO CESAR', 'TORRES DOS SANTOS', '1976', 'AUTOR DESTE BANCO DE DADOS. CARA FODAO...');


-- Insert tabela TT001 -  Sexo 
INSERT INTO SEXO (SG_SEXO, SEXO) VALUE ('M', 'MASCULINO');
INSERT INTO SEXO (SG_SEXO, SEXO) VALUE ('F', 'FEMININO');
INSERT INTO SEXO (SG_SEXO, SEXO) VALUE ('N', 'NAO INFORMADO');

-- Insert valores na tabela tradicional TT002 - PAPEL 
INSERT INTO EXLIBRIS.PAPEL(PAPEL) VALUES ('Autor');
INSERT INTO EXLIBRIS.PAPEL(PAPEL) VALUES ('Tradutor'); 
INSERT INTO EXLIBRIS.PAPEL(PAPEL) VALUES ('Ilustrador'); 
INSERT INTO EXLIBRIS.PAPEL(PAPEL) VALUES ('Apresentador'); 
INSERT INTO EXLIBRIS.PAPEL(PAPEL) VALUES ('Organizador'); 
INSERT INTO EXLIBRIS.PAPEL(PAPEL) VALUES ('Editor'); 
INSERT INTO EXLIBRIS.PAPEL(PAPEL) VALUES ('Prefacio'); 
INSERT INTO EXLIBRIS.PAPEL(PAPEL) VALUES ('Avaliador'); 

-- Insert valores na tabela tradicional TT003 - FORMATO
INSERT INTO EXLIBRIS.FORMATO(FORMATO) VALUES('Hardcover');
INSERT INTO EXLIBRIS.FORMATO(FORMATO) VALUES('Softcover');
INSERT INTO EXLIBRIS.FORMATO(FORMATO) VALUES('Partitura');
INSERT INTO EXLIBRIS.FORMATO(FORMATO) VALUES('Revista');
INSERT INTO EXLIBRIS.FORMATO(FORMATO) VALUES('Fasciculo'); 
INSERT INTO EXLIBRIS.FORMATO(FORMATO) VALUES('Journal');

-- Insert valores na tabela tradicional TT005 - Idioma 
INSERT INTO EXLIBRIS.IDIOMA(SG_IDIOMA_ISO639, IDIOMA, IDIOMA_INGLES) VALUES ('PT','Português', 'Portuguese');
INSERT INTO EXLIBRIS.IDIOMA(SG_IDIOMA_ISO639, IDIOMA, IDIOMA_INGLES) VALUES ('EN','Ingles', 'English');
INSERT INTO EXLIBRIS.IDIOMA(SG_IDIOMA_ISO639, IDIOMA, IDIOMA_INGLES) VALUES ('FR','Frances', 'French');
INSERT INTO EXLIBRIS.IDIOMA(SG_IDIOMA_ISO639, IDIOMA, IDIOMA_INGLES) VALUES ('DE','Alemao', 'German');
INSERT INTO EXLIBRIS.IDIOMA(SG_IDIOMA_ISO639, IDIOMA, IDIOMA_INGLES) VALUES ('EL','Grego', 'Greek');
INSERT INTO EXLIBRIS.IDIOMA(SG_IDIOMA_ISO639, IDIOMA, IDIOMA_INGLES) VALUES ('LA','Latim', 'Latin');

-- Insert tabela TT006 - PAIS
INSERT INTO PAIS(SG_PAIS, PAIS) VALUES('BR','Brasil'); 
INSERT INTO PAIS(SG_PAIS, PAIS) VALUES('CA','Canada'); 
INSERT INTO PAIS(SG_PAIS, PAIS) VALUES('US','United States'); 
INSERT INTO PAIS(SG_PAIS, PAIS) VALUES('DE','Deutschland'); 

-- Insert tabela TT007 - ESTADO
INSERT INTO ESTADO(SG_ESTADO, SG_PAIS, ESTADO) VALUES('DF','BR','Distrito Federal');
INSERT INTO ESTADO(SG_ESTADO, SG_PAIS, ESTADO) VALUES('RS','BR','Rio Grande do Sul');
INSERT INTO ESTADO(SG_ESTADO, SG_PAIS, ESTADO) VALUES('QC','CA','Quebec');
INSERT INTO ESTADO(SG_ESTADO, SG_PAIS, ESTADO) VALUES('AB','CA','Alberta');
INSERT INTO ESTADO(SG_ESTADO, SG_PAIS, ESTADO) VALUES('ON','CA','Ontario');
INSERT INTO ESTADO(SG_ESTADO, SG_PAIS, ESTADO) VALUES('NH','US','New Hampshire');
INSERT INTO ESTADO(SG_ESTADO, SG_PAIS, ESTADO) VALUES('VT','US','Vermont');
INSERT INTO ESTADO(SG_ESTADO, SG_PAIS, ESTADO) VALUES('NY','US','New York');


-- Insert valores na tabela tipo TT008 - TIPO_TELEFONE
INSERT INTO TIPO_TELEFONE(SG_TIPO_TELEFONE, TIPO_TELEFONE) VALUES ('R','Residencial');
INSERT INTO TIPO_TELEFONE(SG_TIPO_TELEFONE, TIPO_TELEFONE) VALUES ('B','Bureaux');
INSERT INTO TIPO_TELEFONE(SG_TIPO_TELEFONE, TIPO_TELEFONE) VALUES ('C','Celular');
INSERT INTO TIPO_TELEFONE(SG_TIPO_TELEFONE, TIPO_TELEFONE) VALUES ('F','Fax');

-- Insert valores na tabela tipo TT009 - TIPO_ENDERECO
INSERT INTO TIPO_ENDERECO(SG_TIPO_ENDERECO, TIPO_ENDERECO) VALUES ('R', 'Residencial');
INSERT INTO TIPO_ENDERECO(SG_TIPO_ENDERECO, TIPO_ENDERECO) VALUES ('B', 'Bureau');

-- Insert valores na tabela tipo TT010 - TIPO_EMAIL
INSERT INTO TIPO_EMAIL(SG_TIPO_EMAIL, TIPO_EMAIL) VALUES ('P', 'Pessoal');

-- Insert valores na tabela GENERO
INSERT INTO EXLIBRIS.GENERO(GENERO) VALUES ('Informática');
INSERT INTO EXLIBRIS.GENERO(GENERO) VALUES ('Militaria');
INSERT INTO EXLIBRIS.GENERO(GENERO) VALUES ('Criptografia');
INSERT INTO EXLIBRIS.GENERO(GENERO) VALUES ('Empreendedorismo');
INSERT INTO EXLIBRIS.GENERO(GENERO) VALUES ('Matemática');
INSERT INTO EXLIBRIS.GENERO(GENERO) VALUES ('Eletrônica'); 
INSERT INTO EXLIBRIS.GENERO(GENERO) VALUES ('Literatura');
INSERT INTO EXLIBRIS.GENERO(GENERO) VALUES ('Música');
INSERT INTO EXLIBRIS.GENERO(GENERO) VALUES ('Quadrinhos');
INSERT INTO EXLIBRIS.GENERO(GENERO) VALUES ('Meditação');
INSERT INTO EXLIBRIS.GENERO(GENERO) VALUES ('Reilgião');
